package businesstier.transferobject;
// Generated May 25, 2023, 11:51:25 p.m. by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Activity generated by hbm2java
 */
public class Activity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Type type;
	private Translation translation;
	private Timestamp lastUpdated;
	private Set<Availability> availabilities = new HashSet<Availability>(0);
	private Set<FacilityActivity> facilityActivities = new HashSet<FacilityActivity>(0);

	public Activity() {
	}

	public Activity(Type type, Translation translation) {
		this.type = type;
		this.translation = translation;
	}

	public Activity(Type type, Translation translation, Timestamp lastUpdated, Set<Availability> availabilities,
			Set<FacilityActivity> facilityActivities) {
		this.type = type;
		this.translation = translation;
		this.lastUpdated = lastUpdated;
		this.availabilities = availabilities;
		this.facilityActivities = facilityActivities;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	public Translation getTranslation() {
		return this.translation;
	}

	public void setTranslation(Translation translation) {
		this.translation = translation;
	}

	public Timestamp getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public Set<Availability> getAvailabilities() {
		return this.availabilities;
	}

	public void setAvailabilities(Set<Availability> availabilities) {
		this.availabilities = availabilities;
	}

	public Set<FacilityActivity> getFacilityActivities() {
		return this.facilityActivities;
	}

	public void setFacilityActivities(Set<FacilityActivity> facilityActivities) {
		this.facilityActivities = facilityActivities;
	}

}
