package businesstier.transferobject;
// Generated May 25, 2023, 11:51:25 p.m. by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;
import java.io.Serializable;

/**
 * Address generated by hbm2java
 */
public class Address implements Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Translation translation;
	private String city;
	private String province;
	private String postalCode;
	private String country;
	private double longitude;
	private double latitude;
	private Timestamp lastUpdated;
	private Facility facility;

	public Address() {
	}

	public Address(Translation translation, String city, String province, String postalCode, String country,
			double longitude, double latitude) {
		this.translation = translation;
		this.city = city;
		this.province = province;
		this.postalCode = postalCode;
		this.country = country;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public Address(Translation translation, String city, String province, String postalCode, String country,
			double longitude, double latitude, Timestamp lastUpdated, Facility facility) {
		this.translation = translation;
		this.city = city;
		this.province = province;
		this.postalCode = postalCode;
		this.country = country;
		this.longitude = longitude;
		this.latitude = latitude;
		this.lastUpdated = lastUpdated;
		this.facility = facility;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Translation getTranslation() {
		return this.translation;
	}

	public void setTranslation(Translation translation) {
		this.translation = translation;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	public Timestamp getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

}
