 package businesstier.transferobject;
// Generated May 25, 2023, 11:51:25 p.m. by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;
import java.util.Date;

/**
 * Availability generated by hbm2java
 */

public class Availability implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Facility facility;
	private Activity activity;
	private Timestamp startTime;
	private Timestamp endTime;
	private int isAvailable;
	private Integer minAge;
	private Integer maxAge;
	private Timestamp lastUpdated;

	public Availability() {
	}

	public Availability(Facility facility, Activity activity, Timestamp startTime) {
		this.facility = facility;
		this.activity = activity;
		this.startTime = startTime;
	}

	public Availability(Facility facility, Activity activity, Timestamp startTime, Timestamp endTime, int isAvailable,
			Integer minAge, Integer maxAge, Timestamp lastUpdated) {
		this.facility = facility;
		this.activity = activity;
		this.startTime = startTime;
		this.endTime = endTime;
		this.isAvailable = isAvailable;
		this.minAge = minAge;
		this.maxAge = maxAge;
		this.lastUpdated = lastUpdated;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	public Timestamp getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Timestamp startTime) {
		this.startTime = startTime;
	}

	public Timestamp getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}

	public int getIsAvailable() {
		return isAvailable;
	}

	public void setIsAvailable(int isAvailable) {
		this.isAvailable = isAvailable;
	}

	public Integer getMinAge() {
		return this.minAge;
	}

	public void setMinAge(Integer minAge) {
		this.minAge = minAge;
	}

	public Integer getMaxAge() {
		return this.maxAge;
	}

	public void setMaxAge(Integer maxAge) {
		this.maxAge = maxAge;
	}

	public Timestamp getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
