package businesstier.transferobject;
// Generated May 25, 2023, 11:51:25 p.m. by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Translation translation;
	private City city;
	private Timestamp lastUpdated;
	private Set<Type> types = new HashSet<Type>(0);

	public Category() {
	}

	public Category(Translation translation, City city) {
		this.translation = translation;
		this.city = city;
	}

	public Category(Translation translation, City city, Timestamp lastUpdated, Set<Type> types) {
		this.translation = translation;
		this.city = city;
		this.lastUpdated = lastUpdated;
		this.types = types;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Translation getTranslation() {
		return this.translation;
	}

	public void setTranslation(Translation translation) {
		this.translation = translation;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public Timestamp getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public Set<Type> getTypes() {
		return this.types;
	}

	public void setTypes(Set<Type> types) {
		this.types = types;
	}

}
