package businesstier.transferobject;
// Generated May 25, 2023, 11:51:25 p.m. by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String title;
	private Timestamp lastUpdated;
	private Set<Category> categories = new HashSet<Category>(0);
	private Set<Category> facilities = new HashSet<Category>(0);

	public City() {
	}

	public City(String title) {
		this.title = title;
	}

	public City(String title, Timestamp lastUpdated, Set<Category> categories, Set<Category> facilities) {
		this.title = title;
		this.lastUpdated = lastUpdated;
		this.categories = categories;
		this.facilities = facilities;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Timestamp getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	public Set<Category> getFacilities() {
		return this.facilities;
	}

	public void setFacilities(Set<Category> facilities) {
		this.facilities = facilities;
	}

}
