package businesstier.transferobject;
// Generated May 25, 2023, 11:51:25 p.m. by Hibernate Tools 6.1.7.Final

/**
 * FacilityActivityId generated by hbm2java
 */
public class FacilityActivityId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int activityId;
	private int facilityId;

	public FacilityActivityId() {
	}

	public FacilityActivityId(int activityId, int facilityId) {
		this.activityId = activityId;
		this.facilityId = facilityId;
	}

	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	public int getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(int facilityId) {
		this.facilityId = facilityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityActivityId))
			return false;
		FacilityActivityId castOther = (FacilityActivityId) other;

		return (this.getActivityId() == castOther.getActivityId())
				&& (this.getFacilityId() == castOther.getFacilityId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getActivityId();
		result = 37 * result + this.getFacilityId();
		return result;
	}

}
