package businesstier.transferobject;
// Generated May 25, 2023, 11:51:25 p.m. by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Facility generated by hbm2java
 */
public class Facility implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Address address;
	private Translation translation;
	private City city;
	private String phone;
	private String url;
	private Timestamp lastUpdated;
	private Set<Availability> availabilities = new HashSet<Availability>(0);
	private ReferenceFacilityLocationorigin referenceFacilityLocationorigin;
	private Set<FacilityActivity> facilityActivities = new HashSet<FacilityActivity>(0);

	public Facility() {
	}

	public Facility(Address address, Translation translation, City city) {
		this.address = address;
		this.translation = translation;
		this.city = city;
	}

	public Facility(Address address, Translation translation, City city, String phone, String url,
			Timestamp lastUpdated, Set<Availability> availabilities, ReferenceFacilityLocationorigin referenceFacilityLocationorigin,
			Set<FacilityActivity> facilityActivities) {
		this.address = address;
		this.translation = translation;
		this.city = city;
		this.phone = phone;
		this.url = url;
		this.lastUpdated = lastUpdated;
		this.availabilities = availabilities;
		this.referenceFacilityLocationorigin = referenceFacilityLocationorigin;
		this.facilityActivities = facilityActivities;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Translation getTranslation() {
		return this.translation;
	}

	public void setTranslation(Translation translation) {
		this.translation = translation;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Timestamp getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public Set<Availability> getAvailabilities() {
		return this.availabilities;
	}

	public void setAvailabilities(Set<Availability> availabilities) {
		this.availabilities = availabilities;
	}

	public ReferenceFacilityLocationorigin getReferenceFacilityLocationorigin() {
		return this.referenceFacilityLocationorigin;
	}

	public void setReferenceFacilityLocationorigin(ReferenceFacilityLocationorigin referenceFacilityLocationorigin) {
		this.referenceFacilityLocationorigin = referenceFacilityLocationorigin;
	}

	public Set<FacilityActivity> getFacilityActivities() {
		return this.facilityActivities;
	}

	public void setFacilityActivities(Set<FacilityActivity> facilityActivities) {
		this.facilityActivities = facilityActivities;
	}

}
