package businesstier.transferobject;
// Generated May 25, 2023, 11:51:25 p.m. by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;

/**
 * FacilityActivity generated by hbm2java
 */
public class FacilityActivity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private FacilityActivityId id;
	private Facility facility;
	private Activity activity;
	private Timestamp lastUpdated;

	public FacilityActivity() {
	}

	public FacilityActivity(FacilityActivityId id, Facility facility, Activity activity) {
		this.id = id;
		this.facility = facility;
		this.activity = activity;
	}

	public FacilityActivity(FacilityActivityId id, Facility facility, Activity activity, Timestamp lastUpdated) {
		this.id = id;
		this.facility = facility;
		this.activity = activity;
		this.lastUpdated = lastUpdated;
	}

	public FacilityActivityId getId() {
		return this.id;
	}

	public void setId(FacilityActivityId id) {
		this.id = id;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	public Timestamp getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
