package businesstier.transferobject;
// Generated May 25, 2023, 11:51:25 p.m. by Hibernate Tools 6.1.7.Final

/**
 * LanguageTranslationId generated by hbm2java
 */
public class LanguageTranslationId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String languageId;
	private int translationId;

	public LanguageTranslationId() {
	}

	public LanguageTranslationId(String languageId, int translationId) {
		this.languageId = languageId;
		this.translationId = translationId;
	}

	public String getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(String languageId) {
		this.languageId = languageId;
	}

	public int getTranslationId() {
		return this.translationId;
	}

	public void setTranslationId(int translationId) {
		this.translationId = translationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LanguageTranslationId))
			return false;
		LanguageTranslationId castOther = (LanguageTranslationId) other;

		return ((this.getLanguageId() == castOther.getLanguageId()) || (this.getLanguageId() != null
				&& castOther.getLanguageId() != null && this.getLanguageId().equals(castOther.getLanguageId())))
				&& (this.getTranslationId() == castOther.getTranslationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLanguageId() == null ? 0 : this.getLanguageId().hashCode());
		result = 37 * result + this.getTranslationId();
		return result;
	}

}
