package businesstier.transferobject;
// Generated May 25, 2023, 11:51:25 p.m. by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;

/**
 * LanguageTranslation generated by hbm2java
 */
public class LanguageTranslation implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private LanguageTranslationId id;
	private Language language;
	private Translation translation;
	private String description;
	private Timestamp lastUpdated;

	public LanguageTranslation() {
	}

	public LanguageTranslation(LanguageTranslationId id, Language language, Translation translation,
			String description) {
		this.id = id;
		this.language = language;
		this.translation = translation;
		this.description = description;
	}

	public LanguageTranslation(LanguageTranslationId id, Language language, Translation translation, String description,
			Timestamp lastUpdated) {
		this.id = id;
		this.language = language;
		this.translation = translation;
		this.description = description;
		this.lastUpdated = lastUpdated;
	}

	public LanguageTranslationId getId() {
		return this.id;
	}

	public void setId(LanguageTranslationId id) {
		this.id = id;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public Translation getTranslation() {
		return this.translation;
	}

	public void setTranslation(Translation translation) {
		this.translation = translation;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Timestamp getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
