package businesstier.transferobject;
// Generated May 25, 2023, 11:51:25 p.m. by Hibernate Tools 6.1.7.Final

/**
 * ReferenceFacilityLocationorigin generated by hbm2java
 */
public class ReferenceFacilityLocationorigin implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int facilityId;
	private Facility facility;
	private int locationId;

	public ReferenceFacilityLocationorigin() {
	}

	public ReferenceFacilityLocationorigin(Facility facility, int locationId) {
		this.facility = facility;
		this.locationId = locationId;
	}

	public int getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(int facilityId) {
		this.facilityId = facilityId;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public int getLocationId() {
		return this.locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

}
