package businesstier.transferobject;
// Generated May 25, 2023, 11:51:25 p.m. by Hibernate Tools 6.1.7.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;
import java.util.List;
import java.util.ArrayList;

/**
 * Translation generated by hbm2java
 */
public class Translation implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Timestamp lastUpdated;
//	private Set<Address> addresses = new HashSet<Address>(0);
	private Set<LanguageTranslation> languageTranslations = new HashSet<>();
//	private Set<Category> categories = new HashSet<Category>(0);
//	private Set<Facility> facilities = new HashSet<Facility>(0);
//	private Set<Activity> activities = new HashSet<Activity>(0);
//	private Set<Type> types = new HashSet<Type>(0);

	public Translation() {
	}

	public Translation(Timestamp lastUpdated, Set<Address> addresses, Set<LanguageTranslation> languageTranslations, Set<Category> categories, Set<Facility> facilities,
			Set<Activity> activities, Set<Type> types) {
		this.lastUpdated = lastUpdated;
//		this.addresses = addresses;
		this.languageTranslations = languageTranslations;
//		this.categories = categories;
//		this.facilities = facilities;
//		this.activities = activities;
//		this.types = types;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Timestamp getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}
//
//	public Set<Address> getAddresses() {
//		return this.addresses;
//	}
//
//	public void setAddresses(Set<Address> addresses) {
//		this.addresses = addresses;
//	}
//
	public Set<LanguageTranslation> getLanguageTranslations() {
		return this.languageTranslations;
	}

	public void setLanguageTranslations(Set<LanguageTranslation> languageTranslations) {
		this.languageTranslations = languageTranslations;
	}
//
//	public Set<Category> getCategories() {
//		return this.categories;
//	}
//
//	public void setCategories(Set<Category> categories) {
//		this.categories = categories;
//	}
//
//	public Set<Facility> getFacilities() {
//		return this.facilities;
//	}
//
//	public void setFacilities(Set<Facility> facilities) {
//		this.facilities = facilities;
//	}
//
//	public Set<Activity> getActivities() {
//		return this.activities;
//	}
//
//	public void setActivities(Set<Activity> activities) {
//		this.activities = activities;
//	}
//
//	public Set<Type> getTypes() {
//		return this.types;
//	}
//
//	public void setTypes(Set<Type> types) {
//		this.types = types;
//	}

}
